### ISSUE TITLE
v3 client runtime errors

### ISSUE THREAD

**Issue by bok-at-built** [sam-goodwin/typesafe-dynamodb#33]
Hey @sam-goodwin, I'm still investigating, but I cannot get `typesafe-dynamodb` to work -- my tsc is happy but the code produces a runtime error when it tries to marshall the data:

```
    TypeError: Cannot read properties of undefined (reading '0')

      at Object.<anonymous>.AttributeValue.visit (node_modules/@aws-sdk/client-dynamodb/dist-cjs/models/models_0.js:1319:40)
      at serializeAws_json1_0AttributeValue (node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3134:38)
      at node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3746:20
          at Array.reduce (<anonymous>)
      at serializeAws_json1_0Key (node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3740:34)
      at serializeAws_json1_0GetItemInput (node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:3646:69)
      at serializeAws_json1_0GetItemCommand (node_modules/@aws-sdk/client-dynamodb/dist-cjs/protocols/Aws_json1_0.js:276:27)
      at serialize (node_modules/@aws-sdk/client-dynamodb/dist-cjs/commands/GetItemCommand.js:30:69)
      at node_modules/@aws-sdk/middleware-serde/dist-cjs/serializerMiddleware.js:5:27
      at node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:28
```

This can be easily reproduced if you try to invoke one of the functions in `test/v3-document-client.test.ts` against a locally running db (no need to create the tables since the request fails to serialize before it's sent out; you can basically just move a `get` call from `foo` into the dummy test case). I suspect it has something to do with a mismatched `JsonFormat` and/or a version mismatch in one of the aws dependencies.

Again, I'm still investigating, but I figured you may be able to quickly diagnose the issue since you're much more familiar with these libraries than I am.

**Comment by sam-goodwin** [comment]
Thanks for reporting the error and for investigating. Going to take a deeper look tomorrow now that I have some time. Hopefully should be a quick fix.

**Comment by sam-goodwin** [comment]
Looks like the problem is that we're using the `GetItemCommand` from `@aws-sdk/client-dynamodb` instead of `GetCommand` from `@aws-sdk/lib-dynamodb`. The former is for AttributeValues and the latter is for Documents.
